### ISSUE TITLE
Signing using Extened Private Key

### ISSUE THREAD

**Issue by uaeio** [paulmillr/noble-ed25519#100]
Hello, guys!

I am using a [bip32-Ed25519](https://input-output-hk.github.io/adrestia/static/Ed25519_BIP.pdf) algorithm to generate several extended private keys.

This library allows me to create signatures using private keys (32 bytes). I want to make signature using Extended Private Keys(SHA-512 of the private key).

Can you advise to do with it.

1. Is it possible to add exported function `signWithExtendedPrivateKey` and `signWithExtendedPrivateKeyAsync`?

```javascript
const signWithExtendedPrivateKey = (msg, extendedPrivateKey) => {
    const m = toU8(msg); // RFC8032 5.1.6: sign msg with key sync
    const e = hash2extK(toU8(priv, 64)))  // pub,prfx
    const rBytes = sha512s(e.prefix, m); // r = SHA512(dom2(F, C) || prefix || PH(M))
    return hashFinish(false, _sign(e, rBytes, m)); // gen R, k, S, then 64-byte signature
}
const signWithExtendedPrivateKeyAsync = async (msg, extendedPrivateKey) => {
    const m = toU8(msg); // RFC8032 5.1.6: sign msg with key async
    const e = hash2extK(toU8(extendedPrivateKey, 64)) // pub,prfx
    const rBytes = await sha512a(e.prefix, m); // r = SHA512(dom2(F, C) || prefix || PH(M))
    return hashFinish(true, _sign(e, rBytes, m)); // gen R, k, S, then 64-byte signature
};
const subtle = { signWithExtendedPrivateKey, signWithExtendedPrivateKeyAsync }
export { subtle, ... }
```

2. Is there any other better way to be able to create signature with having only extended private keys?

**Comment by paulmillr** [comment]
https://github.com/paulmillr/ed25519-keygen/blob/main/src/hdkey.ts is this the same thing you’re looking for?

**Comment by whiteand** [comment]
Yes,  I think. Thank you

**Comment by uaeio** [comment]
@paulmillr Thanks, I will try it out.
