### ISSUE TITLE
how to correctly generate signature with version @noble/ed25519 library version 1.7.3 

### ISSUE THREAD

**Issue by Aixoxa** [paulmillr/noble-ed25519#102]
how to correctly generate signature with version 1.7.3 instead As that's the most used version and supports both esm and commonjs.
the other versions are giving compilation error when compiled with typescript in an electron app.
![Screenshot_2024-05-19_012653](https://github.com/paulmillr/noble-ed25519/assets/53108906/b722ca8a-3259-496a-9228-04c5273f32c3)

**Comment by paulmillr** [comment]
signature generation is described in README
