### ISSUE TITLE
Silent message transformation can happen with v2.0.0

### ISSUE THREAD

**Issue by makew0rld** [paulmillr/noble-ed25519#104]
This is fixed in v2.1.0. But in the previous version, if an invalid message type was passed to `signAsync`, for example any type of `Object`, instead of an error being raised, the message would be silently set to an empty byte array like `new Uint8Array()`. This means a good signature would be returned, but one completely untied from the original message.

This is fixed now, but I thought I would mention it since it really bit me, and it might be worth publicizing that people should upgrade to v2.1.0 ASAP and re-run their tests.

**Comment by paulmillr** [comment]
Thanks. Added this to changelog.
