### ISSUE TITLE
The handling of `S` during verification is badly broken

### ISSUE THREAD

**Issue by Yawning** [paulmillr/noble-ed25519#14]
Per the current standards, the valid range for `S` in a signature is `0 <= S < L`.

RFC 8032 (5.1.7):
```
   1.  To verify a signature on a message M using public key A, with F
       being 0 for Ed25519ctx, 1 for Ed25519ph, and if Ed25519ctx or
       Ed25519ph is being used, C being the context, first split the
       signature into two 32-octet halves.  Decode the first half as a
       point R, and the second half as an integer S, in the range
       0 <= s < L.  Decode the public key A as point A'.  If any of the
       decodings fail (including S being out of range), the signature is
       invalid.
```

FIPS 186-5 (Draft) 7.7:
```
1. Decode the first half of the signature as a point R and the second
   half of the signature as an integer s. Verify that the integer s is in
   the range of 0 ≤ s < n. Decode the public key Q into a point Q’. If
   any of the decodings fail, output “reject”.
```

This implementation throws `Point#multiply: invalid scalar, expected positive integer` when `S = 0`, and accepts signatures with `S >= L`.  The latter is particularly concerning because under the RFC 8032 (and or FIPS 186-5) definition of Ed25519, signatures are not supposed to be malleable.

ps: Is this implementation supposed to be using the cofactored verification equation?  A quick glance at the code made me suspect "no", but test vectors from speccheck suggest "yes, but it's incorrect".

pps: It's fine to lift code and comments from curve25519-dalek, but it should probably be credited and follow their license (which isn't MIT).

**Comment by paulmillr** [comment]
> It's fine to lift code and comments from curve25519-dalek, but it should probably be credited and follow their license 

We don't use their Rust code at all. It's new TypeScript code - a simple list that has 8 values. So, the code is different. And I have credited them already here: "Ported from curve25519-dalek".

**Comment by paulmillr** [comment]
Thank you for the report.

> Is this implementation supposed to be using the cofactored verification equation

We are simply using test vectors that are provided by DJB from his reference implementation.

> It's fine to lift code and comments from curve25519-dalek

We don't use their Rust code at all. It's new TypeScript code - a simple list that has 8 values. So, the code is different. And I have credited them already here: "Ported from curve25519-dalek". Or, did you find something else that I did not credit?

**Comment by Yawning** [comment]
> We are simply using test vectors that are provided by DJB from his reference implementation.

That doesn't answer my question.  Quoting RFC 8032:
```
   3.  Check the group equation [8][S]B = [8]R + [8][k]A'.  It's
       sufficient, but not required, to instead check [S]B = R + [k]A'.
```

Is the implementation trying to do the former or the latter?  Regardless of which way of doing verification is used, common test vectors will pass, but there are implications associated with the decision.

I was wondering because visual inspection of the code suggests it does the latter, but test vectors crafted to determine behavior suggest it is doing something quite different, though my visual inspection was cursory.

>We don't use their Rust code at all. It's new TypeScript code - a simple list that has 8 values. So, the code is different. And I have credited them already here: "Ported from curve25519-dalek". Or, did you find something else that I did not credit?

Porting code from one language to another is typically considered creating a derivative work (https://www.gnu.org/licenses/gpl-faq.html#TranslateCode).

We appear to have dramatically different definitions of "new code" (eg: [dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/7c5ba6949197eb7c31226fa6db1b8294fe6c05bf/src/field.rs#L213) vs [noble](https://github.com/paulmillr/noble-ed25519/blob/7789089138153ff2f3430af8803048631d637541/index.ts#L693)).

There's other places, such as most of the current ristretto implementation, among others.  But that's the last I'll say on this subject since it's not my project.

**Comment by paulmillr** [comment]
@Yawning i've forgot that `sqrt_ratio` was also ported.

As for verification, we are using the cofactored one.

**Comment by Yawning** [comment]
> As for verification, we are using the cofactored one.

Ah, I see the commit.  I was wondering because [ed25519-specckeck](https://github.com/novifinancial/ed25519-speccheck) suggested that this was doing `[([8][k]) mod L]A`.

Since you care about performance, `[8](R + [k]A - [S]B) ?= 0` saves 2 multiplies.

**Comment by paulmillr** [comment]
Thanks!

**Comment by paulmillr** [comment]
@Yawning the library no longer uses any dalek code, i've re-implemented RFC8032 and https://tools.ietf.org/html/draft-irtf-cfrg-ristretto255-decaf448-00
