### ISSUE TITLE
ed25519 decode / decompress

### ISSUE THREAD

**Issue by 1000i100** [paulmillr/noble-ed25519#15]
I have ed25519 pubkeys.
I would like to check there validity.
The RFC say how to do that by decoding/decompressing to an x,y point : https://tools.ietf.org/html/rfc8032#page-11

Do y plan to add this to this lib ?

**Comment by paulmillr** [comment]
This one?

https://github.com/paulmillr/noble-ed25519/blob/master/index.ts#L386

**Comment by 1000i100** [comment]
I love you !
