### ISSUE TITLE
ts to mjs/esm export

### ISSUE THREAD

**Issue by 1000i100** [paulmillr/noble-ed25519#16]
Hi, i would like to use noble-ed25519 in es6 with import, and it work when i run it in node but it fail when i try to build a static package.

could you add in npm package a built mjs file with export & export default in it ?

**Comment by paulmillr** [comment]
If it fails when you build a static package, use different bundler or configure your bundler properly. I won't include mjs until it's native in node.js

**Comment by 1000i100** [comment]
> I won't include mjs until it's native in node.js
It is :
https://nodejs.org/docs/latest-v15.x/api/esm.html#esm_modules_ecmascript_modules

> If it fails when you build a static package, use different bundler or configure your bundler properly.
I will try.

**Comment by paulmillr** [comment]
okay, that sounds good. I'll see what's possible when node v16 is out.
