### ISSUE TITLE
Elligator support

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/noble-ed25519#18]
https://loup-vaillant.fr/articles/implementing-elligator

It's hard to tell if it's supported for ed25519, or only for curve25519.

Here's the implementation:

```typescript
  static fromRandomHex(hex: Hex) {
    const {a} = CURVE;
    hex = ensureBytes(hex);
    const r = bytesToNumberLE(hex);
    const ufactor = mod(-ELLIGATOR_NON_SQUARE * SQRT_M1);
    const vfactor = sqrtMod(ufactor);

    let t1 = mod(r**2n * ELLIGATOR_NON_SQUARE)    // r1
    let u  = t1 + 1n           // r2
    let t2 = mod(u**2n)
    let t3 = mod((a**2n * t1 - t2) * a) // numerator
    t1 = mod(t2 * u)               // denominator
    const inv = invertSqrt(t3 * t1);
    const is_square = inv.isValid;
    t1 = inv.value;
    u  = mod(r**2n * ufactor)
    let v  = mod(r * vfactor)
    if (is_square) u = 1n;
    if (is_square) v = 1n;
    v  = mod(v * t3 * t1)
    t1 = mod(t1**2n)
    u  = mod(u * -a * t3 * t2 * t1)
    if (is_square != (v > (CURVE.P - 1n) / 2n)) // XOR
        v = mod(-v)
    return new Point(mod(u), mod(v))
  }

  toRandomHex() {
    let u = this.x;
    let v_is_negative = this.y > (CURVE.P - 1n) / 2n
    let t = u + CURVE.a;
    let r = -ELLIGATOR_NON_SQUARE * u * t
    let inv = invertSqrt(r);
    let is_square = inv.isValid;
    let isr = inv.value;
    if (!is_square) return;
    if (v_is_negative) u = t
    r = u * isr
    if (r > (CURVE.P - 1n) / 2n) r = mod(-r);
    return numberToHex(r);
  }
```

**Comment by LoupVaillant** [comment]
Hi,

From what I can tell, this piece of code only handles the Montgomery curve (Curve25519). To support Ed25519, a couple more steps are needed:

* After geting (u, v) from `fromRandomHex()`, we must convert them to Edwards. If we stick to an internal projective or extended internal representation of the Edwards point, we can even avoid an additional exponentiation.
* Before feeding (u, v) to `toRandomHex()`, we must convert from Edwards coordinates. This time we require an additional inversion.

Conversion to Edwards25519:

    x = sqrt(-486664) * u / v
    y = (u-1) / (u+1)

Conversion to Curve25519:

    u = (1+y) / (1-y)
    v = sqrt(-486664) * u / x

**Comment by paulmillr** [comment]
@LoupVaillant hey. Seems like we need to know sign (+-) to do curve => ed. https://blog.filippo.io/using-ed25519-keys-for-encryption/

>This means that for each X25519 public key, there are two possible secret scalars (k and -k) and two equivalent Ed25519 public keys (with sign bit 0 and 1, also said to be one the negative of the other).

**Comment by LoupVaillant** [comment]
Yes we do.

The implementation of `fromRandomHex()` above  provides both the _u_ and _v_ coordinates, so we implicitly have the sign of _v_. (Also note that it's easier to make the conversion with _v_ than just its sign: no need to perform point decompression).

In the reverse order, Edwards25519 points have both _x_ and _y_ coordinates, so you can easily convert those to (_u_, _v_), then get the sign of _v_.

**Comment by LoupVaillant** [comment]
(What I mean is: you seem to imply that the implementation you've shown would not be enough to recover the sign we need. My point is that it is.)

**Comment by paulmillr** [comment]
ah, that makes sense. thanks.

**Comment by paulmillr** [comment]
Done in noble-curves
