### ISSUE TITLE
Uncaught TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by tarvos21** [paulmillr/noble-ed25519#20]
```
"use strict";
/*! noble-ed25519 - MIT License (c) Paul Miller (paulmillr.com) */
Object.defineProperty(exports, "__esModule", { value: true });
exports.utils = exports.verify = exports.sign = exports.getPublicKey = exports.SignResult = exports.Signature = exports.Point = exports.ExtendedPoint = exports.CURVE = void 0;
const CURVE = {
    a: -1n,
    d: 37095705934669439343138083508754565189542113879843219016388785533085940283555n,
    P: 2n ** 255n - 19n,
    n: 2n ** 252n + 27742317777372353535851937790883648493n,
    h: 8n,
    Gx: 15112221349535400772501151409588531511454012693041857206046113283949847762202n,
    Gy: 46316835694926478169428394003475163141307993866256225615783033603165251855960n,
};
```

When useded Browser, the browser will throw an error, 'cannot convert a BitInt value to a number'.

How to solve this? Thanks!

**Comment by paulmillr** [comment]
Used how? Show us the code.

**Comment by tarvos21** [comment]
> Used how? Show us the code.

we import `noble-ed25519` in starcoin.js to generate private key and public key: https://github.com/starcoinorg/starcoin.js/blob/a9bb7101d17712effe8b9893ce874b90b1ed84e1/src/encoding/index.ts#L3

then we import `starcoin.js` in starcoin blockchain explorer
https://github.com/starcoinorg/starcoin-explorer/blob/e8d10c4b25cc6506dbc4b401c9726689d85dc4ac/src/modules/Transactions/components/Detail/index.tsx#L

In the starcoin-explorer repo, it's ok to run `yarn start` when developing, and when trying to run `yarn build`,  we can get the built static websites. But the website will throw the `Can not convert a BigInt value to a number` error.

**Comment by paulmillr** [comment]
Everything is working on my machine. You need to specify exactly which browser you're using, and provide an easily reproducible example. I won't download and execute full repo because of security reasons. Debug the error by yourself and tell exactly where's the error is getting thrown in noble-ed code; or provide a 5-line js example that I can execute.

**Comment by tarvos21** [comment]
I use the latest version of Chrome and Safari.

The error is thron here: 

```
const CURVE = {
    a: -1n,
    d: 37095705934669439343138083508754565189542113879843219016388785533085940283555n,
    P: 2n ** 255n - 19n,
    n: 2n ** 252n + 27742317777372353535851937790883648493n,
    h: 8n,
    Gx: 15112221349535400772501151409588531511454012693041857206046113283949847762202n,
    Gy: 46316835694926478169428394003475163141307993866256225615783033603165251855960n,
};
``
```

`P: 2n ** 255n - 19n`, the browser cannot convert variable like `2n` or `255n` to number automatically. It's supported in Node.js, but not in browser yet.

**Comment by paulmillr** [comment]
Bigints are supported in all major browser, including Safari and Chrome. See https://caniuse.com/bigint

I've executed your code in console and everything worked fine.

**Comment by paulmillr** [comment]
Look for errors in your bundler, not in this library.
