### ISSUE TITLE
Uncaught TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by magland** [paulmillr/noble-ed25519#23]
Using this with typescript / react-scripts, I am getting an error in the production / transpiled code (even though it works in my dev version).

```
"use strict";
/*! noble-ed25519 - MIT License (c) Paul Miller (paulmillr.com) */
Object.defineProperty(exports, "__esModule", { value: true });
exports.utils = exports.verify = exports.sign = exports.getPublicKey = exports.SignResult = exports.Signature = exports.Point = exports.ExtendedPoint = exports.CURVE = void 0;
const CURVE = {
    a: -1n,
    d: 37095705934669439343138083508754565189542113879843219016388785533085940283555n,
    P: 2n ** 255n - 19n,
    n: 2n ** 252n + 27742317777372353535851937790883648493n,
    h: 8n,
    Gx: 15112221349535400772501151409588531511454012693041857206046113283949847762202n,
    Gy: 46316835694926478169428394003475163141307993866256225615783033603165251855960n,
};
```

```
index.js:8 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Object.<anonymous> (index.js:8)
    at Object.<anonymous> (6.c1d27334.chunk.js:2)
    at u ((index):1)
    at Object.<anonymous> (main.75bcf584.chunk.js:1)
    at Object.49 (main.75bcf584.chunk.js:1)
    at u ((index):1)
    at Object.134 (main.75bcf584.chunk.js:1)
    at u ((index):1)
    at Module.781 (main.75bcf584.chunk.js:1)
```

Same error on chrome and firefox.

I can provide more detail if needed.

**Comment by paulmillr** [comment]
Why is react-scripts transpiler changing the code at all? The error is not in noble, the error is in your configuration of transpiler.

**Comment by magland** [comment]
I didn't realize that another user submitted the same error report a few weeks ago. I don't know how to fix my transpiler config and I haven't been able to track down exactly why this is happening. I am using tweetnacl for now, even though I think it is slower. I'll check back later on to see if things have resolved (perhaps on the typescript/react side) and then switch back. Kind of mysterious since it works perfectly in my dev environment.

**Comment by paulmillr** [comment]
Your transpiler does not work properly with bigints/bigintegers. 
Either that, or it's trying to convert 1 ** 2 to Math.pow(1,2) which does not work with bigints. 

This is a new js feature that noble is using. That's why it probably was unnoticed. You need to report this issue to create react app.

**Comment by MM0819** [comment]
I have the same issue @magland 

Did you manage to fix it?

**Comment by magland** [comment]
@MM0819 I have been using tweetnacl for now, but would switch back to this project if this particular issue is resolved. Apparently it is an issue with bigint and the transpiler (not noble-ed25519), but I can't switch transpiler nor the tsconfig for now...

**Comment by paulmillr** [comment]
There would be more and more packages using bigints. There is no point in "fixing" it in just one pkg. You should really report the issue to transpiler issue tracker, whatever it is.

**Comment by ramilexe** [comment]
Here is solution for this issue: https://github.com/0xs34n/starknet.js/issues/37#issuecomment-955797303

**Comment by wk3368** [comment]
> Here is solution for this issue: [0xs34n/starknet.js#37 (comment)](https://github.com/0xs34n/starknet.js/issues/37#issuecomment-955797303)

add this section in your package.json:

"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }

and most importantly, dont forget to `rm -rf node_modules/.cache` before `yarn build`

**Comment by paulmillr** [comment]
0c9f122e97fd96052d6f32146285675582196f18 makes sure bigint `**` is never used. With this change, and new release, the library now works in React Native 0.70.

**Comment by srayo16** [comment]
Thanks @wk3368 brother, it's really working. I had that issue since last day and had serious pressure from CEO, now solved it! Thanks again brother.

**Comment by AbbasNaqvi10** [comment]
> > Here is solution for this issue: [0xs34n/starknet.js#37 (comment)](https://github.com/0xs34n/starknet.js/issues/37#issuecomment-955797303)
> 
> add this section in your package.json:
> 
> ```
> "browserslist": {
>     "production": [
>       "chrome >= 67",
>       "edge >= 79",
>       "firefox >= 68",
>       "opera >= 54",
>       "safari >= 14"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   }
> ```
> 
> and most importantly, dont forget to `rm -rf node_modules/.cache` before `yarn build`

Hi,
I have tried it but not working for me

**Comment by 0x1af2aec8f957** [comment]
@AbbasNaqvi10 
You just need to make sure the version of `chrome` is no less than `52` to use it normally.
Try removing the rest of the compile configuration items about `browserslist`, leaving only `chrome >= 52`.

**Comment by paulmillr** [comment]
@jasondesante and?

**Comment by jasondesante** [comment]
> [@jasondesante](https://github.com/jasondesante) and?

The solution is 

"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }


just like mentioned many other places lol. 

The thing that I'm confused about is how this has made older packages not work that used to work but the old packages haven't updated, but noble updated? I used to be able to make builds of my site fine, the packages that caused the error hadn't been updated, but somehow these old packages are now causing an issue.  Anyhoo, doing that thing fixed it.  I just want to understand why and how lol. It's still quite a mystery to me lol.

**Comment by paulmillr** [comment]
@jasondesante You're using babel.js to transpile new features to old syntax (`2 ** 3` => `Math.pow(2, 3)`).

Previously you've just been targeting old browsers (using browserslist) which only supported Math.pow(). Now you're targetting newer browsers which also support `2 ** 3`.

Something somewhere got broken because old code is not new code. Besides math.pow, there have been tons of other transpilation changes done in babel.js. Maybe they aren't done now.

**Comment by paulmillr** [comment]
Thing I don't understand is why this shit keeps appearing after ~4 years. Which bundlers /  tools still use outdated browserslist?

**Comment by jasondesante** [comment]
Either way thanks for posting the answer and being so quick to respond Paul!
