### ISSUE TITLE
Clarify docs about msg hashes

### ISSUE THREAD

**Issue by lunter2** [paulmillr/noble-ed25519#27]
https://datatracker.ietf.org/doc/html/rfc8032#section-7.1

-----TEST 2

ALGORITHM:
Ed25519

SECRET KEY:
4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb

PUBLIC KEY:
3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c

MESSAGE (length 1 byte):
72

SIGNATURE:
92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00

https://paulmillr.com/ecc/

Private key in hex (pasted): 4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb
Public keys (computed OK): 3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c
Message to sign: r
Signature ed: ea22ec953464e2c2b33730b2330fba98bdd675f9f2127d40e4cf53ca1792c3f563fabce1b76bbcba83cdb687e433c9737c5417d3f629ebc811c92119eae6960e

Invalid signature!

**Comment by paulmillr** [comment]
as the vectors say, they accept **bytes** and you're passing utf8 strings on utf8 calculator

```
sec = '4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb'
msg = '72'
nobleEd25519.default.sign(msg, sec).then(console.log)
>92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00
```

**Comment by lunter2** [comment]
Ok, but "r" in UTF-8 is still one byte 0x72.

**Comment by paulmillr** [comment]
so what is happening there is something like this:

```
    const msgb = new TextEncoder().encode(msg);
    const privateKey = priv.replace(/^0x/, '');
    const hash = arrayToHex(await ed25519.utils.sha512(msgb));
    ed.sign(hash, privateKey)
```

The reason for this is simple: 99.99% of the time you sign message hashes, not messages themselves. I should clarify this and renew calculator.

**Comment by lilnasy** [comment]
Hashing the message seems like boilerplate code you'd have to write everytime you want to sign or verify. How do you feel about making the library handle it?

ed.sign(msgHash, privateKey) -> ed.sign(msg, privateKey)
ed.verify(signature, msgHash, publicKey) -> ed.verify(signature, msg, publicKey)

**Comment by paulmillr** [comment]
Sure. Two problems:

1. Backwards-compatibility
2. Are we 100% sure users aren't going to use non-sha512 hashes?

**Comment by lilnasy** [comment]
Nevermind my comment. I got the impression from the docs that hashing was a necessary step, but I was able to use it to verify content after a bit of trial and error.

**Comment by paulmillr** [comment]
@lilnasy I've just checked ed25519 usage. The hash function actually differs from time to time in different apps. It could be sha256, or it could be sha3 etc. So we won't handle this in lib, obviously.

**Comment by lilnasy** [comment]
Yeah, I agree.
For my purposes, it wasn't even necessary.

**Comment by paulmillr** [comment]
We are now disallowing non-hex strings. And i've improved the calculator docs
