### ISSUE TITLE
Suggest clarifying comments and argument names

### ISSUE THREAD

**Issue by covert-encryption** [paulmillr/noble-ed25519#32]
Your library is most interesting and I like the clear bignum implementation. However, it could be good to more clearly mark which functions work in Ed25519, which do in Curve25519, which parameters and points and which scalars, or whether they are in bignum or buffer format. There are a very few comments and sometimes the arguments are named in a way where this is not at all apparent, at least unless one is already familiar with this field.

**Comment by paulmillr** [comment]
Thanks for the feedback.

Are you using TypeScript, or js with vscode type hints? TypeScript shows all types which makes it very simple to reason about.

**Comment by covert-encryption** [comment]
Just browsing on Github so far. Heard of this library today.

**Comment by paulmillr** [comment]
@covert-encryption Are you browsing **index.ts**, or **index.js**?

**Comment by covert-encryption** [comment]
Ah, I didn't realise that was compiled code. Yes, index.ts solves the type problem at least. Perhaps at some points still could use clarification on which curve was used but I did not look too closely yet.

**Comment by paulmillr** [comment]
Well, this library is called noble-ed25519, which means it's always ed25519 (edwards curve), not curve25519 (montgomery). Why did you think it's curve25519?

**Comment by covert-encryption** [comment]
There is at least a conversion function for it, and I saw variables u and v being mentioned in a few places. Also the field element code (arithmetic mod 2^255-19) should be compatible with both if I am not mistaken. But if this is indeed intended to only support Ed25519, I will consider this issue closed.
