### ISSUE TITLE
Uncaught TypeError: can't convert BigInt to number

### ISSUE THREAD

**Issue by sunydev** [paulmillr/noble-ed25519#34]
Hi I have this message when i run npm run build for a github page 
i do not have this message when i run npm start 

Thanks

**Comment by paulmillr** [comment]
Report this to your app bundler, this is not tech support forum

**Comment by binkiebinkie** [comment]
I also receive this error when running the command `yarn build` in a React app that is using the package noble-ed25519. I believe it is related to Babel. 

![error](https://user-images.githubusercontent.com/48534322/147784300-e10d51e4-ac02-4390-bbf6-bab5f3a50357.PNG)

**Comment by binkiebinkie** [comment]
For anyone else encountering this issue I was able to overcome it by installing the @babel/plugin-syntax-bigint package in my React app. So I ran `yarn add @babel/plugin-syntax-bigint`, then in my babel.config.json file I added it to the plugins array like so:

```
{
  "plugins": ["@babel/plugin-syntax-bigint"]
}
```

Also, wherever you are deploying it to don't forget to clear your cache/delete node_modules

https://babeljs.io/docs/en/babel-plugin-syntax-bigint

**Comment by paulmillr** [comment]
Hey folks, a quick heads up: bigint literals is no longer required as per 1.3.3, so shitty build tools could proceed with `noble/ed25519` without hassle.
