### ISSUE TITLE
ESM support breaks importing the default export (as it doesn't exist any more)

### ISSUE THREAD

**Issue by achingbrain** [paulmillr/noble-ed25519#39]
The new ESM support requires use of named exports.  This is better, but anyone `import`ing the old CJS version as a default export was broken by the update.

E.g.  worked with 1.3.0, is broken with 1.3.1:

```js
import ed from '@noble/ed25519'
```

with:
```
import ed from '@noble/ed25519';
       ^^
SyntaxError: The requested module '@noble/ed25519' does not provide an export named 'default'
```

**Comment by paulmillr** [comment]
We never suggested to use default imports, so I don't think this is a problem
