### ISSUE TITLE
Deno: better solution instead of import map

### ISSUE THREAD

**Issue by sgwilym** [paulmillr/noble-ed25519#40]
Currently using this module with Deno requires you to use an import map which aliases `crypto` to `https://deno.land/std@0.119.0/node/crypto.ts`.

This causes two issues:

- This pulls in a massive amount of code for Deno to recreate Node's crypto, _which is then not even used_. This is especially relevant when using a Deno codebase with noble-ed25519 to create a bundle intended for the web.
- It requires all downstream dependents of ed25519 to require an import map. I'm contributing to a project which is a dependency itself, and would require all my users to use noble-ed25519's import map to make it work.

At first glance I'm not entirely sure how to work around this without having a web specific variant of noble-ed25519 that doesn't check for the presence of node's crypto module.

**Comment by paulmillr** [comment]
I've just did what needs to be done to make it work on deno. If you know a better way, propose it. The dependency is a stdlib.

**Comment by paulmillr** [comment]
Keep in mind that we need to be also compatible with ESM and Common.js requires.

**Comment by sgwilym** [comment]
Sure, I'll have a look into how we can make everyone happy. :)

Another thing to consider: even though Deno supports the web crypto API, it will always use `std/node/crypto` with the current implementation.

**Comment by Miaourt** [comment]
Hello, any updates on this topic ?

https://github.com/paulmillr/noble-ed25519/blob/main/index.ts#L9
Why not simply *add* the import when building nodejs package ? Instead of removing it...

**Comment by paulmillr** [comment]
@Miaourt we need to support browser (no crypto module in browser), node.js (it has crypto) and deno (also no crypto module). If you know a better solution, submit a pull request.

**Comment by sgwilym** [comment]
@paulmillr After having forked this repo and having tried a few configurations to get what I need, I think you want to produce two builds: one for node, and one for runtimes that support web platform APIs (i.e. browser and Deno).

Instead of using one index.js for all platforms and using an import map to fill in for crypto, I recommend doing dependency injection at build time **and** removing all the runtime platform checks.

I'm happy to make a PR for this, but before doing that I'd like to know if that approach sounds reasonable to you?

**Comment by paulmillr** [comment]
We are not using one index.js for all platforms. **deno** uses index.ts. What are you suggesting to do with index.ts? Send a PR, it will need extensive testing. Ensure you've tested it in ESM and deno contexts.
