### ISSUE TITLE
Does sign() take a message or its hash?

### ISSUE THREAD

**Issue by hoffa** [paulmillr/noble-ed25519#43]
The README suggests the first parameter to `sign()` is the message hash:

```js
const msgHash = 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef';
...
  const signature = await ed.sign(msgHash, privateKey);
```

However the implementation suggests the parameter is the message itself, and not necessarily a hash:

https://github.com/paulmillr/noble-ed25519/blob/f2881cbc8ad1b893a21c088ab28b30d749c4918d/index.ts#L818-L820

The [referenced RFC](https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.6) also seems to mention nothing about hashing for the function input:

> The inputs to the signing procedure is the private key, a 32-octet string, and a message M of arbitrary size.

**Comment by paulmillr** [comment]
It's `message`, I should adjust docs.
