### ISSUE TITLE
what is the advantage of  distinguishing crypto.web and crypto.node in utils.sha512

### ISSUE THREAD

**Issue by wk3368** [paulmillr/noble-ed25519#51]
```
sha512: async (message: Uint8Array): Promise<Uint8Array> => {
  if (crypto.web) {
    const buffer = await crypto.web.subtle.digest('SHA-512', message.buffer);
    return new Uint8Array(buffer);
  } else if (crypto.node) {
    return Uint8Array.from(crypto.node.createHash('sha512').update(message).digest());
  } else {
    throw new Error("The environment doesn't have sha512 function");
  }
},
```

because 
- both of them(crypto.web.subtile.digest and crypto.node.createHash) will generate the same result,
- and crypto.node.createHash can be used in browser env,
- and the build out js file size are almost the same

why not delete the crypto.web one, and make it a sync function?

```
sha512: (message: Uint8Array): Uint8Array => {
  return Uint8Array.from(crypto.node.createHash('sha512').update(message).digest());
},
```

**Comment by paulmillr** [comment]
There is no require("crypto") in browsers. It is node.js-only. If your build tool adds require("crypto"), it is non-standard.
