### ISSUE TITLE
Passing Uint8Array to `sign` leads to `TypeError: hexToBytes: expected string, got object.` when polyfilling `TextEncoder`

### ISSUE THREAD

**Issue by joepio** [paulmillr/noble-ed25519#58]
First off: thanks so much for this library!

I'm trying to run some tests in a Jest setup (which uses JSDom), and I get this error when calling `sign`:

`TypeError: hexToBytes: expected string, got object`.

I'm sure I'm passing a `Uint8Array`, and the types say it's allowed.

This is my code:

```ts
import { sign, getPublicKey, utils } from '@noble/ed25519';

export const signToBase64 = async (
  message: string,
  privateKeyBase64: string,
): Promise<string> => {
  const privateKeyArrayBuffer = decodeB64(privateKeyBase64);
  const privateKeyBytes: Uint8Array = new Uint8Array(privateKeyArrayBuffer);
  // Polyfill for node
  if (typeof TextEncoder === 'undefined') {
    global.TextEncoder = require('util').TextEncoder;
  }
  const utf8Encode = new TextEncoder();
  const messageBytes: Uint8Array = utf8Encode.encode(message);
  console.log(typeof messageBytes, messageBytes.constructor.name);
  console.log(typeof privateKeyBytes, privateKeyBytes.constructor.name);
  const signatureHex = await sign(messageBytes, privateKeyBytes);
  const signatureBase64 = encodeB64(signatureHex);
  return signatureBase64;
};
```

I think [this](https://github.com/paulmillr/noble-ed25519/blob/edeb48a685c386b8b2d5b4be6b7dc5c432839e05/index.ts#L845) might be where things go wrong. 

There are no issues when running the code in my browser. Maybe `hex instanceof Uint8Array` is false, because the Uint8Array is different from the one I'm using when polyfilled? If that's the case, it might make sense to do `hex.constructor.name == 'Uint8Array'` instead.

**Comment by paulmillr** [comment]
We have tests for this. Works for me:

```
sign(new Uint8Array(32), new Uint8Array(32))
```

So, there is an error in your code

**Comment by joepio** [comment]
Well, that's probably because you're not polyfilling TextEncode, which probably in my case returns a different type of Uint8Array, which does not pass the instanceOf check. Not sure this can be fixed in my code, because your type checking may be too strict.

Is using constructor.name an option perhaps?

**Comment by paulmillr** [comment]
why are you polyfilling textencoder? what environment are you using? Can you write down exact versions?

**Comment by joepio** [comment]
Thanks for the quick replies and helping out @paulmillr 

I'm polyfilling because my testing env (JSDom) does [not yet support `TextEncode`](https://github.com/jsdom/jsdom/issues/2524).

I'm using:

```
@noble/ed25519  1.6.0 
nodejs 17.3.0
jest  27.3.1
```

[Here's the full code](https://github.com/joepio/atomic-data-browser/blob/3d7bf13355202cb8de082612c55d7dfedaabfac9/lib/src/commit.ts)

**Comment by paulmillr** [comment]
Report this to jsdom. We won't change our test for uint8array because there are few very subtle caveats which I don't remember. E.g treating buffers as ui8as and things.
