### ISSUE TITLE
Sync version of sign?

### ISSUE THREAD

**Issue by petertorelli** [paulmillr/noble-ed25519#61]
Thanks for creating this simple, compact, easy-to-use library. Any chance you could make a Sync version of sign to avoid promises?

**Comment by paulmillr** [comment]
Not really a goal for now, we've been audited, would require a new audit etc.

**Comment by petertorelli** [comment]
Gotcha, thanks!

**Comment by paulmillr** [comment]
actually i've went ahead and added this.

**Comment by petertorelli** [comment]
Cool, thanks!
