### ISSUE TITLE
ed25519ph/HashEdDSA support?

### ISSUE THREAD

**Issue by brandonros** [paulmillr/noble-ed25519#63]
> HashEdDSA, shortened as Ed25519ph when coupled with Edwards25519 (and where ph stands for "prehash").

**Comment by paulmillr** [comment]
What's your use case?

**Comment by zamicol** [comment]
Like ECDSA, we use systems that signs digests.  ES224, ES256, ES384, ES512 work well with this.  

PureEdDSA needs the original message and does not work well with this.  It would be awesome to have ed25519ph that conforms to same design pattern as ECDSA.

**Comment by paulmillr** [comment]
How should the ph api look like to be simple?

**Comment by brandonros** [comment]
```java
import java.security.Security;
import com.secunet.ed25519ph.SecunetEdDSASecurityProvider;
Security.addProvider((Provider)new SecunetEdDSASecurityProvider());

// ed25519ph (HashEdDSA / Edwards25519 + prehash)
  public static String signChallenge(String privateKeyHex, String challengeHex) {
    try {
      byte[] decodedPrivateKey = hexStringToByteArray(privateKeyHex);
      byte[] data = hexStringToByteArray(challengeHex);
      PKCS8EncodedKeySpec privKeySpec = new PKCS8EncodedKeySpec(decodedPrivateKey);
      KeyFactory keyFact = KeyFactory.getInstance("EdDSA", "SNED25519");
      PrivateKey privateKey = keyFact.generatePrivate(privKeySpec);
      Signature signature = Signature.getInstance("SHA512withEdDSA", "SNED25519");
      signature.initSign(privateKey);
      signature.update(data);
      byte[] digest = signature.sign();
      return byteArrayToHexString(digest);
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }
```

I doubt this helps much but I ran into this in the wild in Java land and I Googled basically... how to recreate this in JavaScript land and got pretty far down the rabbit hole until I noticed Ed25519ph isn't supported by this library. Just adding context.

**Comment by zamicol** [comment]
How about `signDigest` and `verifyDigest`?

Looking at this [line](https://github.com/paulmillr/noble-ed25519/blob/main/mod.ts#L11):

```Javascript
export { getPublicKey, sign, verify, utils, CURVE, Point, ExtendedPoint, RistrettoPoint };
```

The exported would become:

```
export { getPublicKey, sign, verify, signDigest, verifyDigest, utils, CURVE, Point, ExtendedPoint, RistrettoPoint };
```

**Comment by paulmillr** [comment]
fixed in github.com/paulmillr/noble-curves
