### ISSUE TITLE
Support key generation from seed as described in RFC 8032 section 5.1.5

### ISSUE THREAD

**Issue by zamicol** [paulmillr/noble-ed25519#64]
Looking through the project, I did not see key generation from seed as describe in [RFC 8032 section 5.1.5](https://datatracker.ietf.org/doc/html/rfc8032#section-5.1.5).  

I would suggest  ignoring the RFC's term "private key" and follow Go's term "seed".  It makes the functions more readable while differentiating private key and seed.

Go's NewKeyFromSeed:
https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/crypto/ed25519/ed25519.go;l=116

And Go's SetBytesWithClamping
https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/crypto/internal/edwards25519/scalar.go;l=138;drc=7846e25418a087ca15122b88fc179405e26bf768;bpv=1;bpt=1

I would also point out Filippo's comment: 
> [I]t is lost to history why RFC 8032 adopted the irrelevant RFC 7748 clamping, but it is now required for compatibility.

**Comment by paulmillr** [comment]
I don't understand. There's getPublicKey?

**Comment by paulmillr** [comment]
getPublicKey and getExtendedPublicKey

**Comment by zamicol** [comment]
Thank you, but I don't think "private key" (not "seed") is being exported.  It looks like seed (which is named `PrivKey`) is given, public key, named `pointBytes` is returned, but the private key is not exposed anywhere.  

`getPublicKey` only returns the public key and `getExtendedPublicKey` [itself isn't exported](https://github.com/paulmillr/noble-ed25519/blob/ffdc7026d70297754a825f6e991426188891d1de/mod.ts#L11).  

In function ["getExtendedPublicKey"](https://github.com/paulmillr/noble-ed25519/blob/main/index.ts#L904), I need `scalar`.

Either:
- A. From `getExtendedPublicKey`, `scalar`, which is bigint, needs to be exported in some way  or 
- B. a new function that returns the private key bytes from `scalar`, like `getPublicKey`, should be created.

For comparison with the Go package, 
>This package refers to the RFC 8032 private key as the “seed”.

https://pkg.go.dev/crypto/ed25519

**Comment by paulmillr** [comment]
utils.getExtendedPublicKey is exported and a bit described in readme.

**Comment by zamicol** [comment]
For anyone in the future sharing my confusion:

What [TweetNaCL ](https://tweetnacl.js.org/#/sign), [Go](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/crypto/ed25519/ed25519.go;drc=b0c49ae9f59d233526f8934262c5bbbe14d4358d;l=74), and other packages call the "private key" and is simply the seed concatenated with the public key.

**Comment by paulmillr** [comment]
It's a shame they use 64-byte private keys:

1. 64 > 32, it's harder to store
2. The second (public) part of the 64-byte key can be corrupted e.g. by replacing one letter with another. This way, the private key would correspond to slightly different pubkey, and it could create all kinds of issues
3. All other curves specify private key = private key, w/o pub key
