### ISSUE TITLE
What are your sources for the algorithm?

### ISSUE THREAD

**Issue by javajosh** [paulmillr/noble-ed25519#79]
I did not see a reference of any kind to your source for the ed25518 algorithm design.

Did you implement it from the original paper (https://ed25519.cr.yp.to/ed25519-20110926.pdf)? Or did you adapt it from another codebase, for example done in C or C++?

**Comment by paulmillr** [comment]
See readme, second paragraph

>Conforms to RFC7748, RFC8032 and ZIP215

**Comment by javajosh** [comment]
Does that include the derivation of the magic numbers in the beginning of your implementation?

**Comment by javajosh** [comment]
I was able to find those RFCs without a problem. However, I'm not familiar with ZIP215 or where to find it. Is this what you're referring to: https://zips.z.cash/zip-0215 ?

**Comment by javajosh** [comment]
@paulmillr Hey paul, can you please answer about zip 215 at least?

**Comment by paulmillr** [comment]
The "magic numbers" are specified in specifications. Every single one. 

ZIP215 is at the url you've pasted.

**Comment by javajosh** [comment]
You are as kind as you are helpful.
