### ISSUE TITLE
v2 throws error in FF when bundled with parcel

### ISSUE THREAD

**Issue by TimDaub** [paulmillr/noble-ed25519#84]
```
Error: etc.sha512Sync not set
    err index.js:11
    sha512s index.js:234
    getExtendedPublicKey index.js:248
    getPublicKey index.js:250
    generateKeyPair App.js:8
    App App.js:13
    Preact 5
    ["8lqZg"]< index.js:5
    newRequire index.959aab6e.js:71
    <anonymous> index.959aab6e.js:122
    <anonymous> index.959aab6e.js:145
index.js:11:32
```

I started using this lib in this boilerplate: https://github.com/SafdarJamal/preact-boilerplate
and when I fired up my FF, I got the above error message which then GPT4 suggested me to substitute ed.etc.sha512Sync with a function from crypto-browserify, lol
However, I then downgraded to v1.7.3 and now it works.

**Comment by paulmillr** [comment]
Also keep in mind upgrading notes from readme: getPublicKey is now sync, which requires etc.sha512Sync to be set. See readme how. Use getPublicKeyAsync if you need in-browser version
