### ISSUE TITLE
How to create hybrid NPM package for Node.js and bundlers?

### ISSUE THREAD

**Issue by jost-s** [paulmillr/noble-ed25519#89]
I've seen the hint to shim for Node.js <= v18 to augment the global object with webcrypto features, and it works fine when executing in a Node environment. However, when my package that is importing @noble/ed25519 is bundled, the bundler stumbles over the node module import.

A workaround is a conditional async import. That makes all operation asynchronous and the bundlers are outputting warnings and polyfill suggestions.

What is your recommendation for creating a hybrid package with ed25519 that works in Node.js as well as with a bundler?

**Comment by paulmillr** [comment]
>What is your recommendation for creating a hybrid package with ed25519 that works in Node.js as well as with a bundler

Use noble-curves. It supports hybrid modules and there is no need for a polyfill.

All other solutions that can be implemented in noble-ed25519 will make the library unloadable in browsers without bundlers.

**Comment by paulmillr** [comment]
The choice for every library is between:

- Support old node.js versions and common.js; prohibit browsers (ESM)
- Support browsers (ESM) as-is

**Comment by jost-s** [comment]
Thank you for your answers, I didn't receive notifications about them (something wrong with my settings). I understand, makes sense. I'll switch to noble-curves.
