### ISSUE TITLE
Error: crypto.getRandomValues must be defined

### ISSUE THREAD

**Issue by KirisakiAria** [paulmillr/noble-ed25519#90]
![image](https://github.com/paulmillr/noble-ed25519/assets/20788476/255bee8b-7a2f-4d2c-b194-108e9346fa6f)
![image](https://github.com/paulmillr/noble-ed25519/assets/20788476/51a8de92-a862-402c-9576-6e6fee3b4457)

**Comment by paulmillr** [comment]
https://github.com/paulmillr/noble-ed25519#usage

**Comment by rdzidziguri** [comment]
I have the same problem; the link above does not explain much. I am running it on Node 18.

**Comment by paulmillr** [comment]
@rdzidziguri which words, exactly, you don't understand from the link above?

> For node.js <= 18 and React Native, additional polyfills are needed

**Comment by rdzidziguri** [comment]
@paulmillr, I scrolled down, and it is there, but it would be better if you put those right under the statement with explicit text for each ENV. There was confusion right after that statement, followed by the code I misinterpreted thinking it was the one for the earlier node.

**Comment by paulmillr** [comment]
@rdzidziguri do you think 2 is better than 1?

<img width="599" alt="a" src="https://github.com/paulmillr/noble-ed25519/assets/574696/d5eed476-b703-4279-8bfa-06d728d15e5f">
<img width="608" alt="b" src="https://github.com/paulmillr/noble-ed25519/assets/574696/19f7f480-c6c0-4709-b8fc-cecab3d7677c">
