### ISSUE TITLE
React Native compatibility issue

### ISSUE THREAD

**Issue by Cali93** [paulmillr/noble-ed25519#91]
The package breaks when running on a React Native environment.
I think it's because React Native doesn't support crypto by default.

Is there a recommended way to get it working on React Native (with and without using Expo) ?
Could you document the steps ?

### Steps to reproduce:

```bash
npx create-expo-app my-ed25519-app
```

Update the App.tsx with the following code:

```tsx
import { StyleSheet, Text, View } from "react-native";
import { useEffect } from "react";
import * as ed25519 from "@noble/ed25519"; // ESM-only. Use bundler for common.js
// import * as Crypto from "expo-crypto";
// @ts-ignore
// if (!globalThis.crypto) globalThis.crypto = Crypto;
// import { sha512 } from "@noble/hashes/sha512";
// ed25519.etc.sha512Sync = (...m) => sha512(ed25519.etc.concatBytes(...m));

export default function App() {
  useEffect(() => {
    (async () => {
      console.log("Generating random priv key");
      const privateKey = ed25519.utils.randomPrivateKey();
      console.log("privateKey: ", { privateKey });

      const publicKey = ed25519.getPublicKey(privateKey);
      console.log("privateKey: ", { publicKey });

      const pubKeyHex = ed25519.etc.bytesToHex(publicKey).toLowerCase();
      const privKeyHex = ed25519.etc.bytesToHex(privateKey).toLowerCase();
      console.log("Digest: ", { pubKeyHex, privKeyHex });
    })();
  }, []);

  return (
    <View style={styles.container}>
      <Text>Crypto Module Example</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
```
This will result in
```bash
Error: crypto.getRandomValues must be defined
Error: crypto.getRandomValues must be defined
```

The other issue is that since 2.0 I get the following error.
<img width="1166" alt="Capture d’écran 2023-05-18 à 14 48 15" src="https://github.com/paulmillr/noble-ed25519/assets/32299095/202ec0f3-8724-4f96-acd6-2135cf46787a">

If you uncomment lines from 4 to 8 it will work as expected but that's only for expo apps which provide expo-crypto.
If using React Native CLI it's not as easy and as clean as using a module such as expo-crypto.

**Comment by paulmillr** [comment]
>I think it's because React Native doesn't support crypto by default.

It's all supported. Something is wrong with your config.

You will need to write down the exact steps and errors.

**Comment by Cali93** [comment]
I updated the issue with more details and steps to reproduce.
I face the same issue using node 16 and 18.

**Comment by paulmillr** [comment]
Okay. It seems like React Native still doesn't support webcrypto: https://github.com/facebook/hermes/issues/915.

>Is there a recommended way to get it working on React Native (with and without using Expo) ? Could you document the steps ?

Use polyfill. There should be some, because a lot of people are using noble with webcrypto.

I don't develop RN apps so I can't say which one I would recommend.

**Comment by paulmillr** [comment]
@Cali93 if you'll find something good, please post it here - I will want to add it to README for documentation purposes

**Comment by Cali93** [comment]
Most of the library is working by using [react-native-quick-crypto](https://www.npmjs.com/package/react-native-quick-crypto) to polyfill crypto.
However I get `Cannot read property 'digest' of undefined` when calling `sign` or `signAsync`.
