### ISSUE TITLE
Random PRNG - how secure is it?

### ISSUE THREAD

**Issue by mangoplane** [paulmillr/noble-ed25519#93]
Hi Paul,

Great work. Just wondering how secure the random number generator used for seeding keygen. Any chance you could elaborate on that in your documentation? Also, is there any chance we can provide a source of entropy, say from hardware or random.org?

Kind regards.

**Comment by paulmillr** [comment]
It's using browser's https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues which is considered cryptographically secure.

> Also, is there any chance we can provide a source of entropy, say from hardware or random.org

You can do whatever you want, but to me using `random.org` seems like a terrible idea.

Best thing to do is to verify the entropy randomness by yourself.

**Comment by paulmillr** [comment]
Adjusted the documentation.
